[package]
name = "crawler"
version = "1.0.0"
authors = ["thatlittlegit <wapidstyle@live.ca>"]

[dependencies]
reqwest = "0.8.5"
htmlstream = "0.1.3"
robotparser = "0.10"
url = "1.7.0"
log = "0.4.1"
env_logger = "0.5.6"
regex = "0.2.10"
lazy_static = "1.0.0"
